### ISSUE TITLE
[question] difference with keyring.passwordstore

### ISSUE THREAD

**Issue by Freed-Wu** [nazarewk/keyring_pass#13]
Hey, what is the difference with <https://github.com/stv0g/keyrings.passwordstore>? Thanks!

**Comment by nazarewk** [comment]
After peeking at the code the premise of both implementations is similar, but:
- this version has some configuration options (prefix in password store & setting custom pass binary)
- the other version supports multiline (aka metadata) entries, where usable password is just the first line

I consciously omitted the multiline entries because it is implementation/backend specific feature of which `keyring` itself is not aware.
